mimosa:
  web:
    strict: false
  security:
    enabled: false

spring:
  application:
    name: 1922 System

logging:
  level:
    sql: DEBUG
    tw.com.fcb.mimosa: debug
    com.zaxxer.hikari.HikariConfig: DEBUG
    jdbc:
      resultsettable: INFO
      sqltiming: INFO
      sqlonly: FATAL
      audit: FATAL
      resultset: FATAL
      connection: FATAL
log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
  trim:
    sql:
      extrablanklines: false
